services:

  _defaults:
    autowire: true
    autoconfigure: true
    # public: true

  Codesache\AddRelCanonicalBundle\:
    resource: '../src/'
    exclude: '../src/{ContaoManager,DependencyInjection,Helper,Model,Controller/FrontendModule/Legacy}'
